# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-sandwich" do
  name "git-sandwich"
  desc "A Git diff validator that rejects changes outside BEGIN/END blocks"
  homepage "https://github.com/n0h0/git-sandwich"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-sandwich"

  on_macos do
    on_intel do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_darwin_amd64.tar.gz"
      sha256 "4419cd654034e1916b0cf4d09123758019e5997ab45b17deebaf9100d640ebd8"
    end
    on_arm do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_darwin_arm64.tar.gz"
      sha256 "70962cdd0bb11f841338934d519193ee1705e6a7c740f71315e2d479470688b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_linux_amd64.tar.gz"
      sha256 "edb55dc3499c0851ba124c5fb5d4e1767fb0d0f515633c2c6cfc4234be9fb482"
    end
    on_arm do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_linux_arm64.tar.gz"
      sha256 "13da8f6e74b419a3cd59ac93c794dbecbaa5698c016a34fc52caaf34729d8724"
    end
  end

  # No zap stanza required
end
