# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-sandwich" do
  name "git-sandwich"
  desc "A Git diff validator that rejects changes outside BEGIN/END blocks"
  homepage "https://github.com/n0h0/git-sandwich"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-sandwich"

  on_macos do
    on_intel do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_darwin_amd64.tar.gz"
      sha256 "bf7285a6121b39313ff4b0d32f2582ac210c497eeecf76f152482cc455468e55"
    end
    on_arm do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_darwin_arm64.tar.gz"
      sha256 "bdf763a0e821337087b9491d85a76d7eeeaa944e6ec6ecde6016b098e3754ada"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_linux_amd64.tar.gz"
      sha256 "d676ca7a3d469bf5cdcb6dda3dce4d9a40fd64a044a0f056213158719878f0ab"
    end
    on_arm do
      url "https://github.com/n0h0/git-sandwich/releases/download/v#{version}/git-sandwich_#{version}_linux_arm64.tar.gz"
      sha256 "f826d74ef573f10a5fc8b3ec6541dd384de110103978ee4dac6c1e56f8a2e875"
    end
  end

  # No zap stanza required
end
